baseURL = "https://elkotito.github.io/"
languageCode = "en-us"
title = "Mateusz Pieniak"
description = "Mateusz Pieniak's Blog on AI, Machine Learning and Software Engineering"
theme = "PaperMod"
canonifyURLs = true
enableRobotsTXT = true

[params]
defaultTheme = "light"
author = "Mateusz Pieniak"
ShowReadingTime = true
ShowPostNavLinks = false
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowToc = true
TocOpen = true
fuse = true
math = true
homeInfoParams = { Title = "Cześć 👋", Content = "I'm Mateusz and I learn in public so AI can be better. Always one print statement away from clarity." }
assets = { customCSS = ["css/extended/custom.css"] }
socialIcons = [
    { name = "github", url = "https://github.com/elkotito" },
    { name = "linkedin", url = "https://linkedin.com/in/mateusz-pieniak/" },
    { name = "rss", url = "/index.xml"}
]

[menu]
main = [
    { name = "Posts", url = "/", weight = 1 },
    { identifier = "search", name = "Search", url = "/search/", weight = 2 },
    { name = "Tags", url = "/tags/", weight = 3 },
    { name = "RSS", url = "/index.xml", weight = 4 }
]


[outputs]
home = ["HTML", "RSS", "JSON"]